CREATE TABLE Country_info(id int, country_name varchar(30), Capitals varchar (20),Currency varchar(20),Total_population bigint , Nationalgame varchar(20),NationalAnimal varchar(20),Nationalflower varchar(20),NationalAnthem varchar(20));
Select*From Country_info;
INSERT INTO Country_info VALUES (1,'India','Delhi','rupees',141.72,'Hockey','Tiger','Lotus','Janaganamana');
INSERT INTO Country_info VALUES (2,'Albania','Tirana','Albanialek',141.72,'Football','Eagle','Redpoppy','Himni i Flamurit');
INSERT INTO Country_info VALUES (3,'Australia','Canberra','Australian dollar',2.7,'Football','kangaroo','Golden Wattle','AdvanceAustraliaFair');
INSERT INTO Country_info VALUES (4,' Botswana','Gaborone','pula',1.63,'Soccer','Zebra','Sengaparile','Fatshe leno la rona');
INSERT INTO Country_info VALUES (5,'Cambodia','Phnom Penh','CambodianRiel',1.86,' KbachKunPradalKhmer','kouprey','Romduol','Nokor Reach');
INSERT INTO Country_info VALUES (6,'Burundi','Gitega','Burundian Franc',1.29,'Football','Transvaal Lion','Bujumbura','Burundi Bwacu"');
INSERT INTO Country_info VALUES (7,'Canada','Ottawa','Dollar',3.89,'ice hockey','Beaver','not_declear','O Canada');
INSERT INTO Country_info VALUES (8,'Djibouti','Djibouti','franc',11.2,'Soccer','elk','Bitterball','Djibouti');
INSERT INTO Country_info VALUES (9,'Egypt','Cairo','Pound',113.7,'Soccer','Steppe eagle.','Nymphaea lotus','Bilady,Bilady');
INSERT INTO Country_info VALUES (10,'Fiji','Suva','Dollar',9.3,'Rugby union','banded iguana','tagimaucia','Meda Dau Doka');
INSERT INTO Country_info VALUES (11,'France','Paris','euro',6.8,'Football','Coney','Iris','La Marseillaise');
INSERT INTO Country_info VALUES (12,'Georgia','Tbilisi','lari',37.1,'Rugby Union','white-tailed deer','Rosa laevigata','Tavisupleba');
INSERT INTO Country_info VALUES (13,'Germany','Berlin','euro',8.38,'Soccer','Golden Eagle','Cornflowers','Lied der Deutschen');
INSERT INTO Country_info VALUES (14,'Grenada','Saint Georges','EastCaribbeanDollar',1.25,'Cricket','Grenada dove','Bougainvillea','Hail Grenada');
INSERT INTO Country_info VALUES (15,'Guinea','Franc','rupees',1.39,'Rugby League ','forest elephant','Vernonia djalonensis','Liberté');
INSERT INTO Country_info VALUES (16,'Hungary','Budapest','Forint',96.4,'Water Polo','Hungarian Wolf','Tulip','Himnusz');
INSERT INTO Country_info VALUES (17,'Israel','Jerusalem','Israeli Shekel',95.6,'Football','no animal','Anemone coronaria','Hatikvah');
INSERT INTO Country_info VALUES (18,'Japan','Tokyo','yen',12.51,'Sumo','green pheasant','cherry blossom','Kimigayo');
INSERT INTO Country_info VALUES (19,' Kenya','Nairobi','Shilling',51044355,'Football','Lions','orchid','Ee Mungu Nguvu Yetu');
INSERT INTO Country_info VALUES (20,'Netherlands','Amsterdam','euro',1.77,'Football','Lion','daisy','Wilhelmus');
delete from Country_info where id=16;
CREATE TABLE Country_details AS SELECT id,country_name,Capitals,NationalAnthem FROM Country_info;
Select*From country_details;
/*AGGRIGATE FUNCTION*/
SELECT count(*) as no_of_rows from country_details;
SELECT SUM(total_population) as total from Country_info where id < 10;
SELECT max(total_population) from Country_info;
SELECT min(total_population) from Country_info;
SELECT AVG(total_population) as avg_population from Country_info;
SELECT COUNT(Capitals), country_name FROM country_info GROUP BY country_name HAVING COUNT(id) < 10;
SELECT SUM(Total_population),country_name From country_info GROUP BY country_name HAVING COUNT(id)<10;