CREATE DATABASE project;
CREATE TABLE Airport_details(id int, airport_name varchar(20), arrival_Time int,departure_Time int ,price_in_Rs int);

CREATE TABLE Cricket_teams(id int, team_name varchar(20),number_of_players int, captain_name varchar(20), coach_name varchar(20));
ALTER TABLE Airport_details ADD COLUMN locations varchar(20);
ALTER TABLE Airport_details ADD COLUMN cities varchar(20);
ALTER TABLE Airport_details ADD COLUMN type_of_airport varchar(20);
select* from  Airport_details;
ALTER TABLE Cricket_teams ADD COLUMN number_of_wining int;
ALTER TABLE Cricket_teams ADD COLUMN runrate bigint;
ALTER TABLE Cricket_teams ADD COLUMN top_bowlers varchar(20);
select* from  Cricket_teams;
ALTER TABLE Cricket_teams DROP COLUMN number_of_wining;
ALTER TABLE Airport_details DROP COLUMN cities;
ALTER TABLE Airport_details DROP COLUMN airport_detail;

ALTER TABLE  Cricket_teams  DROP COLUMN runrate;
ALTER TABLE  Cricket_teams  DROP COLUMN top_bowlers;

ALTER TABLE Airport_details RENAME COLUMN locations TO located_places;
ALTER TABLE Airport_details RENAME COLUMN type_of_airport TO airport_detail;
ALTER TABLE Cricket_teams modify COLUMN runrate int;

CREATE TABLE Cricket_teams(id int, team_name varchar(20),number_of_players int, captain_name varchar(20), coach_name varchar(20));
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (1,'India',15,'Rohitsharma','RahulDravid');
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (2,'Australia',15,'Pat Cummins','Andrew McDonald');
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (3,'England',15,'Jos Buttler','Brendon McCullum');
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (4,'New Zealand',15,'Kane Williamson','Gary Stead');
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (5,'South Africa',15,'Temba Bavuma','Rob Walter');
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (6,'Pakistan',15,'Babar Azam','Grant Bradburn');
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (7,'Sri Lanka',15,'Dasun Shanaka','Chris Silverwood');
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (8,'West Indies',15,'Shai Hope','Daren Sammy');
select* from  Cricket_teams;
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (9,'Bangladesh',15,'AlHasan','Hathurusingha');
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (10,'Afghanistan',15,'Hashmatullah Shahidi','Jonathan Trott');
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (11,'Ireland',15,'Andrew Balbirnie','Heinrich Malan');
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (12,'Zimbabwe',15,'Craig Ervine','Dave Houghton');
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (13,'Netherlands',15,'Scott Edwards','Ryan Cook');
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (14,'Scotland',15,'Richie Berrington','Doug Watson');
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (15,'Nepal',15,'Rohit Paudel','Monty Desai');
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (16,'UAE',15,'Muhammad Waseem','Robin Singh');
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (17,'Oman',15,'Zeeshan Maqsood','Duleep Mendis');
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (18,'USA',15,'Patel','Arunkumar');
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (19,'Namibia',15,'Gerhard Erasmus','Pierre de Bruyn');
INSERT INTO Cricket_teams(id,team_name,number_of_players,captain_name,coach_name) VALUES (20,'Hong Kong',15,' Nizakat Khan','Trent Johnston');
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (1,'IndraGandhiIA',8,6,4500);
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (2,'IndraGandhiIA',12,10,5000);
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (3,'IndraGandhiIA',4,2,4800);
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (4,'IndraGandhiIA',8,6,5200);
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (5,'ChennaiIA',7,9,5500);
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (6,'Rajiv_Gandhi_IA',8,10,4800);
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (7,'NetajiSubhasCBoseIA',2,4,5200);
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (8,'CochinIA',3,5,4700);
select* from  Airport_details;
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (9,'GoaIA',6,8,6200);
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (10,'SVpatelIA',5,7,5300);
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (11,'Puneairport',11,1,4700);
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (12,'TrivandrumIA',9,11,5100);
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (13,'Jaipur',7,9,4600);
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (14,'Biju Patnaik',8,10,5000);
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (15,'Bagdogra_Airport',1,3,6100);
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (16,'ChandigarhIA',5,7,4400);
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (17,'Veer_SavarkarIA',3,5,6500);
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (18,'DeviAhilya_BaiHolkar',2,4,5800);
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (19,'ChennaiIA',3,5,4700);
INSERT INTO Airport_details(id,airport_name,arrival_Time,departure_Time,price_in_Rs) VALUES (20,'JaipurAirport',3,5,4700);
